# Generated by Django 3.0.2 on 2020-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200210_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
