# Generated by Django 3.0.2 on 2020-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_email_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.URLField(default='https://p7.hiclipart.com/preview/948/13/258/video-game-game-controller-joystick-online-game-vector-gamepad-thumbnail.jpg'),
        ),
        migrations.AlterField(
            model_name='game',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='game',
            name='times_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
