# Generated by Django 3.0.2 on 2020-02-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200210_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalgameinfo',
            name='times_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalgameinfo',
            name='high_score',
            field=models.FloatField(default=0.0),
        ),
    ]
