# Generated by Django 3.0.2 on 2020-02-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200210_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='Nameless game', max_length=255),
        ),
    ]
