# Generated by Django 3.0.2 on 2020-02-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200211_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(default='https://users.aalto.fi/~oseppala/game/example_game.html'),
        ),
    ]
