# Generated by Django 3.0.2 on 2020-02-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200211_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
