# Generated by Django 3.0.2 on 2020-02-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200212_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='times_downloaded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
