# Generated by Django 3.0.2 on 2020-02-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_game_times_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_download',
            field=models.DateTimeField(null=True),
        ),
    ]
